import type PgBoss from "pg-boss";
import type { BaseLogger } from "pino";
import nodemailer from "nodemailer";
import { getPgDb, schema } from "@rvl/db-postgres";
import { and, eq, inArray, sql } from "drizzle-orm";

import { Jobs } from "./jobs.js";

type DeliverPayload = { deliveryId: string };

function getTransport() {
  // Minimal industrial-safe default:
  // - if SMTP env vars are missing, deliveries will be marked failed with a clear error.
  const host = process.env.SMTP_HOST;
  const port = process.env.SMTP_PORT ? Number(process.env.SMTP_PORT) : undefined;
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  if (!host || !port || !user || !pass) {
    return null;
  }

  return nodemailer.createTransport({
    host,
    port,
    secure: process.env.SMTP_SECURE === "true",
    auth: { user, pass }
  });
}

export async function registerDeliveryWorker(boss: PgBoss, logger: BaseLogger) {
  await boss.work<DeliverPayload>(Jobs.alertDeliver, { teamConcurrency: 5 } as any, async (job: any) => {
    const db = getPgDb();
    const deliveryId = (job.data as DeliverPayload).deliveryId;

    const claimed = await db
      .update(schema.alertDeliveries)
      .set({ status: "sending", attempt: sql`${schema.alertDeliveries.attempt} + 1` })
      .where(and(eq(schema.alertDeliveries.id, deliveryId), inArray(schema.alertDeliveries.status, ["queued", "failed"] as any)))
      .returning();
    const delivery = claimed[0];
    if (!delivery) return;

    const transport = getTransport();
    if (!transport) {
      await db
        .update(schema.alertDeliveries)
        .set({ status: "failed", lastError: "SMTP not configured" })
        .where(eq(schema.alertDeliveries.id, deliveryId));
      return;
    }

    const [evt] = await db.select().from(schema.alertEvents).where(eq(schema.alertEvents.id, delivery.alertEventId));
    if (!evt) return;

    try {
      const subject = `[${evt.severity.toUpperCase()}] ${evt.title}`;
      const text = [
        `Machine: ${evt.machineId}`,
        `Status: ${evt.status}`,
        `Start: ${evt.startsAt.toISOString()}`,
        "",
        evt.description ?? "",
        "",
        "This alert was generated by RVL Lamination Agent."
      ].join("\n");

      await transport.sendMail({
        from: process.env.SENDER_EMAIL ? `${process.env.SENDER_NAME ?? "RVL Agent"} <${process.env.SENDER_EMAIL}>` : userFromTransport(transport),
        to: delivery.destination,
        subject,
        text
      });

      await db
        .update(schema.alertDeliveries)
        .set({ status: "sent", sentAt: new Date(), lastError: null })
        .where(and(eq(schema.alertDeliveries.id, deliveryId), eq(schema.alertDeliveries.status, "sending" as any)));

      logger.info({ deliveryId }, "alert delivered");
    } catch (err: any) {
      await db
        .update(schema.alertDeliveries)
        .set({ status: "failed", lastError: String(err) })
        .where(and(eq(schema.alertDeliveries.id, deliveryId), eq(schema.alertDeliveries.status, "sending" as any)));
      logger.warn({ err: String(err), deliveryId }, "alert delivery failed");
      throw err;
    }
  });
}

function userFromTransport(transport: nodemailer.Transporter): string {
  // nodemailer doesn't expose credentials; keep a safe fallback
  return process.env.SENDER_EMAIL ?? "rvl-agent@localhost";
}

