import type PgBoss from "pg-boss";
import type { BaseLogger } from "pino";
import { getPgDb, schema } from "@rvl/db-postgres";
import { and, eq, inArray, sql } from "drizzle-orm";

import { Jobs } from "./jobs.js";
import { getSmtpTransport, smtpFromAddress } from "../email/smtpTransport.js";

type DeliverPayload = { deliveryId: string };

export async function registerDeliveryWorker(boss: PgBoss, logger: BaseLogger) {
  await boss.work<DeliverPayload>(Jobs.alertDeliver, { teamConcurrency: 5 } as any, async (jobs: any) => {
    for (const job of jobs) {
      const db = getPgDb();
      const deliveryId = (job.data as DeliverPayload).deliveryId;

      const claimed = await db
        .update(schema.alertDeliveries)
        .set({ status: "sending", attempt: sql`${schema.alertDeliveries.attempt} + 1` })
        .where(and(eq(schema.alertDeliveries.id, deliveryId), inArray(schema.alertDeliveries.status, ["queued", "failed"] as any)))
        .returning();
      const delivery = claimed[0];
      if (!delivery) continue;

      const transport = getSmtpTransport();
      if (!transport) {
        await db
          .update(schema.alertDeliveries)
          .set({ status: "failed", lastError: "SMTP not configured" })
          .where(eq(schema.alertDeliveries.id, deliveryId));
        continue;
      }

      const [evt] = await db.select().from(schema.alertEvents).where(eq(schema.alertEvents.id, delivery.alertEventId));
      if (!evt) continue;

      try {
        const subject = `[${evt.severity.toUpperCase()}] ${evt.title}`;
        const text = [
          `Machine: ${evt.machineId}`,
          `Status: ${evt.status}`,
          `Start: ${evt.startsAt.toISOString()}`,
          "",
          evt.description ?? "",
          "",
          "This alert was generated by RVL Lamination Agent."
        ].join("\n");

        await transport.sendMail({
          from: smtpFromAddress(smtpFallbackUser()),
          to: delivery.destination,
          subject,
          text
        });

        await db
          .update(schema.alertDeliveries)
          .set({ status: "sent", sentAt: new Date(), lastError: null })
          .where(and(eq(schema.alertDeliveries.id, deliveryId), eq(schema.alertDeliveries.status, "sending" as any)));

        logger.info({ deliveryId }, "alert delivered");
      } catch (err: any) {
        await db
          .update(schema.alertDeliveries)
          .set({ status: "failed", lastError: String(err) })
          .where(and(eq(schema.alertDeliveries.id, deliveryId), eq(schema.alertDeliveries.status, "sending" as any)));
        logger.warn({ err: String(err), deliveryId }, "alert delivery failed");
        throw err;
      }
    }
  });
}

function smtpFallbackUser(): string {
  return process.env.SMTP_USER ?? process.env.SENDER_EMAIL ?? "rvl-agent@localhost";
}

