import { tool } from "@langchain/core/tools";
import { z } from "zod";
import nodemailer from "nodemailer";
import { config } from "./config";
import { getRecentReadings, getDailyStats, storeAlert } from "./db";

// ── Nodemailer Transporter ────────────────────────────────────────

const transporter = nodemailer.createTransport({
  host: config.SMTP_HOST,
  port: config.SMTP_PORT,
  secure: config.SMTP_SECURE,
  auth: {
    user: config.SMTP_USER,
    pass: config.SMTP_PASS,
  },
});

function _wrapAlertHtml(bodyText: string, severity: string): string {
  const severityColors: any = {
    CRITICAL: "#dc2626",
    ALARM: "#ea580c",
    WARNING: "#d97706",
    ANOMALY: "#2563eb",
    FAULT: "#9333ea",
  };
  const color = severityColors[severity] || "#6b7280";

  return `
  <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: ${color}; color: white; padding: 16px 24px; border-radius: 8px 8px 0 0;">
          <h2 style="margin: 0;">⚠️ ${severity} ALERT</h2>
          <p style="margin: 4px 0 0; opacity: 0.9;">Nonwoven Lamination Machine</p>
      </div>
      <div style="background: #f8f9fa; padding: 24px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
          <pre style="white-space: pre-wrap; font-family: monospace; font-size: 14px; line-height: 1.6;">${bodyText}</pre>
      </div>
      <p style="color: #9ca3af; font-size: 12px; text-align: center; margin-top: 12px;">
          Auto-generated by Nonwoven AI Agent — ${new Date().toISOString()}
      </p>
  </div>
  `;
}

// ── LangChain Tools ───────────────────────────────────────────────

export const sendAlertEmailTool = tool(
  async ({ subject, body, severity }) => {
    if (config.ALERT_RECIPIENTS.length === 0) {
      return "No alert recipients configured. Email not sent.";
    }
    
    try {
      const mailOptions: any = {
        from: `"${config.SENDER_NAME}" <${config.SENDER_EMAIL || config.SMTP_USER}>`,
        to: config.ALERT_RECIPIENTS.join(", "),
        subject: subject,
        text: body,
        html: _wrapAlertHtml(body, severity),
      };

      if (severity === "CRITICAL" || severity === "ALARM") {
        mailOptions.priority = "high";
      }

      await transporter.sendMail(mailOptions);
      return `Alert email sent successfully to ${config.ALERT_RECIPIENTS.join(", ")}`;
    } catch (error: any) {
      return `Failed to send email: ${error.message}`;
    }
  },
  {
    name: "send_alert_email",
    description: "Send an alert email to factory management.",
    schema: z.object({
      subject: z.string().describe("Email subject line including severity and component"),
      body: z.string().describe("Email body text describing the alert, current values, and recommended action"),
      severity: z.string().describe("Alert severity level — CRITICAL, ALARM, WARNING, or ANOMALY"),
    }),
  }
);

export const sendReportEmailTool = tool(
  async ({ subject, html_body }) => {
    if (config.REPORT_RECIPIENTS.length === 0) {
      return "No report recipients configured. Email not sent.";
    }
    
    try {
      await transporter.sendMail({
        from: `"${config.SENDER_NAME}" <${config.SENDER_EMAIL || config.SMTP_USER}>`,
        to: config.REPORT_RECIPIENTS.join(", "),
        subject: subject,
        html: html_body,
        priority: "normal",
      });
      return `Report email sent successfully to ${config.REPORT_RECIPIENTS.join(", ")}`;
    } catch (error: any) {
      return `Failed to send report email: ${error.message}`;
    }
  },
  {
    name: "send_report_email",
    description: "Send a monthly report email with an HTML body.",
    schema: z.object({
      subject: z.string().describe("Email subject line for the monthly report"),
      html_body: z.string().describe("Complete HTML content of the monthly report"),
    }),
  }
);

export const storeAlertRecordTool = tool(
  async ({ tag, severity, message, value, unit }) => {
    try {
      const alertId = storeAlert({
        timestamp: new Date().toISOString(),
        tag,
        label: tag.replace(/_/g, " "),
        value,
        unit,
        level: severity,
        message,
      });
      return `Alert stored in database with ID ${alertId}`;
    } catch (error: any) {
      return `Failed to store alert: ${error.message}`;
    }
  },
  {
    name: "store_alert_record",
    description: "Store an alert record in the database for tracking and reporting.",
    schema: z.object({
      tag: z.string().describe("Machine tag identifier (e.g., EXTRUDER_AMP, WINDER_FAULT)"),
      severity: z.string().describe("Alert severity — CRITICAL, ALARM, WARNING, ANOMALY, or FAULT"),
      message: z.string().describe("Human-readable alert message"),
      value: z.number().describe("Current sensor value that triggered the alert"),
      unit: z.string().describe("Unit of measurement (A, RPM, %, m/min, etc.)"),
    }),
  }
);

export const queryTagHistoryTool = tool(
  async ({ tag_name, hours }) => {
    hours = Math.min(hours || 1, 24);
    try {
      const readings = getRecentReadings(tag_name, hours);
      if (readings.length === 0) {
        return `No readings found for ${tag_name} in the last ${hours} hour(s).`;
      }

      const values = readings.map(r => r.value);
      const sum = values.reduce((a, b) => a + b, 0);
      const summary = {
        tag: tag_name,
        period_hours: hours,
        sample_count: values.length,
        min: Number(Math.min(...values).toFixed(3)),
        max: Number(Math.max(...values).toFixed(3)),
        avg: Number((sum / values.length).toFixed(3)),
        latest: Number(values[values.length - 1].toFixed(3)),
        unit: readings[0].unit,
      };
      return JSON.stringify(summary);
    } catch (error: any) {
      return `Error querying history: ${error.message}`;
    }
  },
  {
    name: "query_tag_history",
    description: "Query recent sensor readings for a specific tag. Use this to get historical context.",
    schema: z.object({
      tag_name: z.string().describe("The tag to query (e.g., EXTRUDER_AMP, LAMINATOR_MPM)"),
      hours: z.number().optional().describe("How many hours of history to retrieve (default 1, max 24)"),
    }),
  }
);

export const getProductionStatsTool = tool(
  async ({ period }) => {
    try {
      let dateStr = period;
      if (period === "today" || !period) {
        dateStr = new Date().toISOString().split("T")[0];
      }
      const stats = getDailyStats(dateStr);
      if (Object.keys(stats).length === 0) {
        return `No production data available for ${dateStr}.`;
      }
      return JSON.stringify(stats, null, 2);
    } catch (error: any) {
      return `Error getting production stats: ${error.message}`;
    }
  },
  {
    name: "get_production_stats",
    description: "Get aggregated production statistics for a given period.",
    schema: z.object({
      period: z.string().describe("Either 'today' or 'YYYY-MM-DD' for a specific date"),
    }),
  }
);
